# Generated by Django 5.2 on 2025-05-03 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='phonenumber',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('product_description', models.TextField()),
                ('cost', models.FloatField(default=0, null=True)),
                ('unit_price', models.FloatField(default=0)),
                ('unit_cost', models.FloatField(default=0)),
                ('total_quantity', models.IntegerField(default=0)),
                ('received_quantity', models.IntegerField(default=0)),
                ('tyep_of_stock', models.CharField(max_length=20)),
                ('product_supplier', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('product_supplier', models.TextField()),
                ('customer_name', models.CharField(max_length=80)),
                ('customer_phone_number', models.CharField(max_length=15)),
                ('amount_received', models.FloatField(default=0)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Mpesa', 'Mpesa'), ('Bank Transfer', 'Bank Transfer')], default='Cash', max_length=20)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stock')),
            ],
        ),
    ]
